# Generated by Django 2.1.7 on 2019-03-07 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='media2/prof_pic')),
                ('Region', models.CharField(choices=[('Bollywood', 'Bollywood'), ('Hollywood', 'Hollywood'), ('Tollywood', 'Tollywood')], max_length=30)),
                ('rating', models.IntegerField()),
                ('Release_year', models.DateTimeField()),
                ('summary', models.TextField()),
                ('Lead_Actor', models.CharField(max_length=15)),
                ('Lead_Actress', models.CharField(max_length=15)),
                ('director', models.CharField(max_length=15)),
                ('Producer', models.CharField(max_length=15)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Release_year',),
            },
        ),
    ]
